### ISSUE TITLE
About the checkpoint

### ISSUE THREAD

**Issue by BoomShakaY** [gengyuanmax/MeVTR#4]
Thanks for your work and the code! 

I have a question about the provided checkpoint. Is it only for the ActivityNet dataset? Or is it also suitable for Charades?

And which fps do you use for training? 

Appreciate it if you could provide more specific guidance, thanks!

**Comment by gengyuanmax** [comment]
Hi, I uploaded the checkpoint for Charades as well.
I sampled 64 frames as in the evaluation scripts, and the same for traininng.
