### ISSUE TITLE
大哥，我又来问您问题了，跪求大哥指点，目前需要引用大哥的文章！

### ISSUE THREAD

**Issue by X7J92** [gengyuanmax/MeVTR#6]
大哥，我有一个问题，您在测试text-to-video方向的任务的时候，Rank值得计算是建立在多个事件的基础上，还是单个事件得基础上呀。你在训练的时候使用的多个事件文本作为查询，您测试的指标rank也是建立在多事件的基础上吗,跪求大哥指点
![d9a63575dd8af3522d8b2b2931d3657](https://github.com/user-attachments/assets/b1fdf7cd-89f6-49ea-afc3-957b1eeea3f3)

**Comment by gengyuanmax** [comment]
> 大哥，我有一个问题，您在测试text-to-video方向的任务的时候，Rank值得计算是建立在多个事件的基础上，还是单个事件得基础上呀。你在训练的时候使用的多个事件文本作为查询，您测试的指标rank也是建立在多事件的基础上吗,跪求大哥指点
> 
> ![d9a63575dd8af3522d8b2b2931d3657](https://github.com/user-attachments/assets/b1fdf7cd-89f6-49ea-afc3-957b1eeea3f3)
> 
> 
> 
> 

是的 建立在多个event的基础上的 不过只有v2t存在多个event 但是反之其实只有一个target video

**Comment by X7J92** [comment]
大哥，我还有个问题，您的论文中在activityNet captions数据集上，您选择val1还是val2作为的测试集呀

**Comment by gengyuanmax** [comment]
我们都是沿用的之前文章的retrieval的设置，用的v2

**Comment by X7J92** [comment]
谢谢您，呜呜呜我又有个问题大哥。您训练模型的时候，每个句子的发生的时间标签信息，用到您的检索模型里面了嘛。目前我在做多事件的检索联合定位，其中定位任务没有用到事件的时间标签，但我发现我的模型在多事件的检索性能和您论文中差了很多。

**Comment by gengyuanmax** [comment]
没有的，我们这个里面不包括localization

Gengyuan Zhang

**Comment by X7J92** [comment]
大哥，我发现您在dataloder中加载了每个句子对应的时间标签，用于构建video的掩码，所以就很困惑。大哥我想加一下您的微信可以嘛，想把您挂在我的论文中，目前准备投稿至2025cvpr。
![1](https://github.com/user-attachments/assets/b1794d71-9e94-40f3-9101-01892e050b0b)
![2](https://github.com/user-attachments/assets/6850167c-53e7-4c52-b285-ccf13449fdce)

**Comment by gengyuanmax** [comment]
不好意思有点误解，我们没有把localization作为任务，但是用这个timestamp来生成video和text的对应关系。

**Comment by gengyuanmax** [comment]
For personal issues please send me emails.
